### ISSUE TITLE
Including cyclone in a gtest fails compilation 

### ISSUE THREAD

**Issue by ichernev** [eclipse-cyclonedds/cyclonedds-cxx#252]
This is the setup:

```
// header.hpp
#include <dds/dds.hpp>
```
```
// main.hpp
#include "header.hpp"

#include <gtest/gtest.h>

class SmokeTest : public ::testing::Test
{};

TEST_F(SmokeTest, testMe) {
    std::map<int, std::string> m;
    EXPECT_EQ(m.end(), m.find(5));
}

int main(int argc, char **argv) {
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
```
[out.log](https://github.com/eclipse-cyclonedds/cyclonedds-cxx/files/8369100/out.log)

The problem seems to be that `TInstanceHandle` contains a constructor from anything:
```
    template <typename ARG0>
    TInstanceHandle(const ARG0& arg0);
```
and also declares `ostream<< operator`, so gtest picks that to print something and it blows up.

I tried adding `explicit` and that did compile (cyclone, and then the example), and work. However I'm seeing more such black-hole constructors, so it should probably be fixed in all places (because having such non-explicit constructors is a recipe for disaster). Another option is to add some template magic to reduce the types of arguments that are accepted to only those that can create a `DELEGATE`.

**Comment by eboasson** [comment]
> The problem seems to be that TInstanceHandle contains a constructor from anything

That sounds really nasty to this non-C++ programmer. A quick check tells me that this is defined in the OMG header files that we did our best to leave untouched, but it seems to me that this is nasty enough that we should not stick to this standpoint. I would not presume to know the tradeoffs in the options you suggest (nor whether any others exist) — but perhaps @e-hndrks has an idea.

In any case, it seems wise to subject all the "black-hole" constructors to the same treatment.

**Comment by ichernev** [comment]
To be fair, using RTI DDS did not fall in the same trap... I will check their headers :)

**Comment by ichernev** [comment]
@e-hndrks any updates on this?

**Comment by e-hndrks** [comment]
I agree that the TInstanceHandle function should have an explicit constructor, and RTI already submitted a ticket about this at the OMG website. I think this wil be processed processed in the next revision of the spec. I would say that it is OK to already anticipate on this and modify the Cyclone header accordingly.

The reason why some classes still need generic constructors that can take a parameter of any type has to do with the way inheritance is handled on the API level. Normal inheritance doesn't work because your API classes are wrappers around vendor specific Delegates, and so when you want to for example upcast a parameter you would have to upcast both the wrapper and its Delegate. Just as an example:
{code}
typedef dds::core::TEntity<org::eclipse::cyclonedds::core::EntityDelegate> dds::core::Entity;
typedef dds::domain::TDomainParticipant<org::eclipse::cyclonedds::domain::DomainParticipantDelegate> dds::domain::DomainParticipant;

// I want to obtain the StatusCondition of a participant, but the constructor for StatusCondition expects a dds::core::Entity.
dds::domain::DomainParticipant dp(1);
dds::core::cond::StatusCondition sc(dp);
{code}
Now to get from my DomainParticipant to Entity (its parent class) should just be an implicit upcast, but it isn't so easy because although the wrapper can be explicitly upcasted, its delegate does not. In other words: dds::core::Entity<DomainParticipantDelegate> != dds::core::Entity<EntityDelegate>.

This is the reason for the spec to provide generic constructors that accept a parameter of any type of class. In this constructor it is then checked if the Delegates can be properly casted into one another as well.

Hope that provides some context.

**Comment by javiersorianoruiz** [comment]
hello.

What is the situation of this issue?, It has been solved?

I have tried to reproduce the problem with the main gtest example indicated by ichernev at the beginning of this issue and I can compile without any errors.

I have also check that the TInstanceHandle constructor has not been changed, and it is still not explicit: 
// line 73, file cyclonedds-cxx/src/ddscxx/include/dds/core/TInstanceHandle.hpp

```
/**
* @cond
* Parametric constructor for creating an instance-handle
* from some other type. This function is intended for internal
* usage.
*/
template <typename ARG0>
TInstanceHandle(const ARG0& arg0);
/** @endcond */

```

I have used:
- cyclonedds-cxx and cyclonedds 0.10.0
- Microsoft Windows Subsystem for Linux (WSL): Ubuntu 20.04 LTS
- gcc 9.4.0
- cmake 3.16.3

Thank you very much

**Comment by ichernev** [comment]
@javiersorianoruiz sorry, I don't have access to the environment any more. From what I can remember we used gcc10+ubuntu20.04LTS, but it was also possibly happening with gcc7+ubuntu20.04LTS. Moreover, I remember that the issue was not trivial to reproduce, if you look at my example there is a header in-between gtest main and cyclone, if you include cyclone directly it works for some weird reason. You also need the std::map in an assert... (so something in gtest prepares to print it).

The solution is to make constructors explicit, if that is not done, then it's not fixed.

**Comment by javiersorianoruiz** [comment]
@ichernev , thank you very much for your answer.

I think that I am using your example properly, as you indicated some time ago, I have a main.cpp with this code:

```
// main.hpp
#include "header.hpp"

#include <gtest/gtest.h>

class SmokeTest : public ::testing::Test
{};

TEST_F(SmokeTest, testMe) {
    std::map<int, std::string> m;
    EXPECT_EQ(m.end(), m.find(5));
}

int main(int argc, char **argv) {
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}

```
In this code you can see the map and the gtest macro EXPECT_EQ which supposes it is enough to reproduce the problem.

And a header.hpp with only this include

`#include <dds/dds.hpp>`

Is there anything I am doing wrong to be able to reproduce the problem?

Kind regards

**Comment by ichernev** [comment]
@javiersorianoruiz well, if you do exactly what I described then "you're doing it right". I'm trying to say it wasn't straight forward to reproduce and if you play around with headers and include order you can make it go away, but the underlying problem persists.

**Comment by javiersorianoruiz** [comment]
Hello again.

We (@Bit-Seq and me) have seen that this issue is related to #162 (or even is the same problem).

In the issue #162, when we compile `cyclonedds-cxx (version 0.10.1)` with `g++11` and `-DBUILD_TESTING=ON` the same compilation error (or very similar) appears:

```
In file included from /usr/local/include/gtest/gtest-matchers.h:48,
                 from /usr/local/include/gtest/internal/gtest-death-test-internal.h:46,
                 from /usr/local/include/gtest/gtest-death-test.h:43,
                 from /usr/local/include/gtest/gtest.h:60,
                 from /root/cyclonedds-cxx/src/ddscxx/tests/Bounded.cpp:12:
/usr/local/include/gtest/gtest-printers.h: In instantiation of 'struct testing::internal::FindFirstPrinter<dds::domain::TDomainParticipant<org::eclipse::cyclonedds::domain::DomainParticipantDelegate>, void, testing::internal::internal_stream_operator_without_lexical_name_lookup::StreamPrinter, testing::internal::ProtobufPrinter, testing::internal::ConvertibleToIntegerPrinter, testing::internal::ConvertibleToStringViewPrinter, testing::internal::RawBytesPrinter, testing::internal::FallbackPrinter>':
/usr/local/include/gtest/gtest-printers.h:286:8:   required from 'struct testing::internal::FindFirstPrinter<dds::domain::TDomainParticipant<org::eclipse::cyclonedds::domain::DomainParticipantDelegate>, void, testing::internal::ContainerPrinter, testing::internal::FunctionPointerPrinter, testing::internal::PointerPrinter, testing::internal::internal_stream_operator_without_lexical_name_lookup::StreamPrinter, testing::internal::ProtobufPrinter, testing::internal::ConvertibleToIntegerPrinter, testing::internal::ConvertibleToStringViewPrinter, testing::internal::RawBytesPrinter, testing::internal::FallbackPrinter>'
/usr/local/include/gtest/gtest-printers.h:306:9:   required from 'void testing::internal::PrintWithFallback(const T&, std::ostream*) [with T = dds::domain::TDomainParticipant<org::eclipse::cyclonedds::domain::DomainParticipantDelegate>; std::ostream = std::basic_ostream<char>]'
/usr/local/include/gtest/gtest-printers.h:440:30:   [ skipping 2 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/usr/local/include/gtest/gtest-printers.h:999:30:   required from 'void testing::internal::UniversalPrint(const T&, std::ostream*) [with T = dds::domain::TDomainParticipant<org::eclipse::cyclonedds::domain::DomainParticipantDelegate>; std::ostream = std::basic_ostream<char>]'
/usr/local/include/gtest/gtest-printers.h:884:19:   required from 'static void testing::internal::UniversalTersePrinter<T>::Print(const T&, std::ostream*) [with T = dds::domain::TDomainParticipant<org::eclipse::cyclonedds::domain::DomainParticipantDelegate>; std::ostream = std::basic_ostream<char>]'
/usr/local/include/gtest/gtest-printers.h:1037:44:   required from 'std::string testing::PrintToString(const T&) [with T = dds::domain::TDomainParticipant<org::eclipse::cyclonedds::domain::DomainParticipantDelegate>; std::string = std::__cxx11::basic_string<char>]'
/usr/local/include/gtest/gtest-printers.h:333:36:   required from 'static std::string testing::internal::FormatForComparison<ToPrint, OtherOperand>::Format(const ToPrint&) [with ToPrint = dds::domain::TDomainParticipant<org::eclipse::cyclonedds::domain::DomainParticipantDelegate>; OtherOperand = dds::core::null_type; std::string = std::__cxx11::basic_string<char>]'
/usr/local/include/gtest/gtest-printers.h:414:45:   required from 'std::string testing::internal::FormatForComparisonFailureMessage(const T1&, const T2&) [with T1 = dds::domain::TDomainParticipant<org::eclipse::cyclonedds::domain::DomainParticipantDelegate>; T2 = dds::core::null_type; std::string = std::__cxx11::basic_string<char>]'
/usr/local/include/gtest/gtest.h:1412:63:   required from 'testing::AssertionResult testing::internal::CmpHelperOpFailure(const char*, const char*, const T1&, const T2&, const char*) [with T1 = dds::domain::TDomainParticipant<org::eclipse::cyclonedds::domain::DomainParticipantDelegate>; T2 = dds::core::null_type]'
/usr/local/include/gtest/gtest.h:1436:1:   required from 'testing::AssertionResult testing::internal::CmpHelperNE(const char*, const char*, const T1&, const T2&) [with T1 = dds::domain::TDomainParticipant<org::eclipse::cyclonedds::domain::DomainParticipantDelegate>; T2 = dds::core::null_type]'
/root/cyclonedds-cxx/src/ddscxx/tests/Bounded.cpp:47:9:   required from here
/usr/local/include/gtest/gtest-printers.h:290:36: error: no matching function for call to 'testing::internal::internal_stream_operator_without_lexical_name_lookup::StreamPrinter::PrintValue(const dds::domain::TDomainParticipant<org::eclipse::cyclonedds::domain::DomainParticipantDelegate>&, std::nullptr_t)'
  290 |     T, decltype(Printer::PrintValue(std::declval<const T&>(), nullptr)),
      |                 ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/gtest/gtest-printers.h:213:15: note: candidate: 'template<class T, class, class> static void testing::internal::internal_stream_operator_without_lexical_name_lookup::StreamPrinter::PrintValue(const T&, std::ostream*)'
  213 |   static void PrintValue(const T& value, ::std::ostream* os) {
      |               ^~~~~~~~~~
/usr/local/include/gtest/gtest-printers.h:213:15: note:   template argument deduction/substitution failed:
/usr/local/include/gtest/gtest-printers.h:212:33: error: no match for 'operator<<' (operand types are 'std::basic_ostream<char>' and 'const dds::domain::TDomainParticipant<org::eclipse::cyclonedds::domain::DomainParticipantDelegate>')
  211 |             typename = decltype(std::declval<std::ostream&>()
      |                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  212 |                                 << std::declval<const T&>())>
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~

```

Kind Regards

**Comment by eboasson** [comment]
I had a vague hope that monkey-see-monkey-do using the comments @e-hndrks but even a slightly extended variant of it still results in tons of errors regarding outputting something-whatever-blabla using the output operator (*). There's got to be someone who knows C++ way better than I do who can help! That would be much preferable to me whacking the compiler over the metaphorical head with a block (spruce, naturally) until it gives up its resistance ...

(*) The one that so weirdly has been misappropriated as a left-shift operator that it boggles the mind. How could they not have realised in 1972? Tongue-in-cheek, of course, but still ... user-defined operators while only allowing for some predefined symbols and with fixed precedence rules?

**Comment by javiersorianoruiz** [comment]
Finally, I have been able to reproduce the compilation problem, I have had to create a container with docker with the following environment.
- Docker version 20.10.17, build 100c701
- Ubuntu 20.04 LTS
- google test 1.12.1
- cyclonedds-cxx and cyclonedds 0.10.0
- gcc 11.1.0 (in our old environment where the problem it wasn't reproduce we were using gcc 9.4.0, the rest of tools and sw had the same version)
- cmake 3.16.3

I have written this DockerFile

```
FROM        ubuntu:20.04

# update and install dependencies
RUN         apt-get update \
                && apt-get install -y \
                    software-properties-common \
                    wget \
                && add-apt-repository -y ppa:ubuntu-toolchain-r/test \
                && apt-get update \
                && apt-get install -y \
                    make \
                    git \
                    curl \
                    vim \
                && apt-get install -y cmake \
                && apt-get install -y gcc-11 \
                && apt-get install -y g++-11 \
                && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100 \
                && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 100

WORKDIR /root/

#cyclonedds compilation and installation
RUN git clone https://github.com/eclipse-cyclonedds/cyclonedds.git --branch 0.10.1
WORKDIR /root/cyclonedds/
RUN mkdir build
WORKDIR /root/cyclonedds/build
RUN cmake -DCMAKE_INSTALL_PREFIX=/usr/local/lib/cyclonedds -DBUILD_EXAMPLES=ON ..
RUN cmake --build .
RUN cmake --build . --target install

#googletest compilation and installation
WORKDIR /root/
RUN git clone https://github.com/google/googletest.git -b release-1.12.1
WORKDIR /root/googletest/
RUN mkdir build
WORKDIR /root/googletest/build
RUN cmake ..
RUN make
RUN make install



#cyclonedds-cxx compilation and installation
WORKDIR /root/
RUN git clone https://github.com/eclipse-cyclonedds/cyclonedds-cxx.git --branch 0.10.1
WORKDIR /root/cyclonedds-cxx/
RUN mkdir build
WORKDIR /root/cyclonedds-cxx/build
RUN cmake   -DCMAKE_INSTALL_PREFIX=/usr/local/lib/cyclonedds-cxx \
            -DCMAKE_PREFIX_PATH=/usr/local/lib/cyclonedds \
#If I compile with the test of gtest appears the compilation error issue 252
#https://github.com/eclipse-cyclonedds/cyclonedds-cxx/issues/252
#            -DBUILD_TESTING=ON \
            -DBUILD_EXAMPLES=ON \
            -DCMAKE_BUILD_TYPE=Debug \
            ..
RUN cmake --build .
RUN cmake --build . --target install

#copy and compilation example to reproduce issue 252
#https://github.com/eclipse-cyclonedds/cyclonedds-cxx/issues/252
WORKDIR /root/
ADD issue_252 /root/issue_252
RUN rm -rf /root/issue_252/build
RUN mkdir /root/issue_252/build
WORKDIR /root/issue_252/build/
RUN cmake ..
RUN make
```

With this environment I have also been able to reproduce the other related issue (#162)

**Comment by javiersorianoruiz** [comment]
With the commit 09b5807faacdd6c8d0189a82935f8cecfaec9769 and its respective pull request (#324), we have indicated a possible workaround, that allows solving both issues (#162 and #252).

It permits to compile the binary test (issue #252) and the unitary tests in the library cyclonedds-cxx (issue #162)
