### ISSUE TITLE
Question about serialize performance of non primative type array

### ISSUE THREAD

**Issue by skysky97** [eclipse-cyclonedds/cyclonedds-cxx#315]
There is a issue posted in ros2 [tuning guid](https://docs.ros.org/en/humble/How-To-Guides/DDS-tuning.html).

> Issue: Sending custom messages with large variable-sized arrays of non-primitive types causes high serialization/deserialization > overhead and CPU load. 

I have tested this case and it shows cyclonedds-cxx spends much more time on serialization than cyclonedds does.Is this the right behavior or anything else I should take care of？

**Comment by eboasson** [comment]
ROS 2 doesn't use the Cyclone C++ binding, but rather builds directly on the C API with a custom serialiser that converts directly between ROS 2 messages and CDR. That's what that tuning guide refers to.

That said, the C++ binding shouldn't be much slower than the C code. In fact, it ought to be faster because the C++ one specialises code where the C one has a simple VM with some recursive calls. The C++ code did improve quite a bit in the 0.10 release, so if you were using an older version, it may be easily resolved.

Otherwise, would it be possible to share a flame graph or a small reproducer so someone can look at it?

**Comment by skysky97** [comment]
![perf_c](https://user-images.githubusercontent.com/18086458/189068165-2c0e5a40-5247-488e-8526-b81d4165748b.svg)
![perf_cxx](https://user-images.githubusercontent.com/18086458/189068208-df49cbc9-20ee-40fd-8f13-abe240261691.svg)

I'm using v0.9.1 but with a merge of pull request for #261.  The released 0.9.1 has a worse performance in above case, and I found this issue #261 about performance too. As at that time the 0.10 was not released yet,  I merged #261 manually in may workspace. The test result shows a great improve, but not as good as the c api one.

Also a vtune profiler hotspots summary:

Top Hotspots
    Function	Module	CPU Time	% of CPU Time
    __libc_sendmsg	libc.so.6	0.890s	26.9%
    org::eclipse::cyclonedds::core::cdr::cdr_stream::align	libddscxx.so.0	0.681s	20.6%
    __memmove_avx_unaligned_erms	libc.so.6	0.150s	4.5%
    org::eclipse::cyclonedds::core::cdr::write<org::eclipse::cyclonedds::core::cdr::basic_cdr_stream, (bool)1>.constprop.0	Publisher	0.140s	4.2%
    org::eclipse::cyclonedds::core::cdr::cdr_stream::next_entity	libddscxx.so.0	0.124s	3.8%
    [Others]	N/A*	1.325s	40.0%

Top Hotspots
    Function	Module	CPU Time	% of CPU Time
    __libc_sendmsg	libc.so.6	1.110s	70.3%
    dds_cdr_alignto_clear_and_resize	libddsc.so.0	0.190s	12.0%
    dds_stream_write_adrLE	libddsc.so.0	0.080s	5.1%
    dds_stream_write_implLE	libddsc.so.0	0.040s	2.5%
    ddsrt_sendmsg	libddsc.so.0	0.030s	1.9%
    [Others]	N/A*	0.130s	8.2%

**Comment by reicheratwork** [comment]
> ps: After update to 0.10.2rc1, test result shows no difference.

Hello @skysky97 , just to follow up, do you mean no more difference between C and C++, or no difference in performance between your v0.9.1 + PR#271 and v0.10.2rc1 ?

**Comment by eboasson** [comment]
Thanks @reicheratwork for noticing that this issue had interesting updates to it (that I missed) and picking it up. And of course my apologies to you @skysky97. Fortunately, you're in good hands with @reicheratwork digging into your issue. ☺️

(I'm still not sure if I get an notification mail from GitHub when a comment is edited ... but let's assume the problem is with me and not with GitHub ...)
